// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraderPro.Infrastructure.Persistence;

#nullable disable

namespace TraderPro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TraderProDbContext))]
    [Migration("20260729141935_AddTwoDeviceProcurementPocFoundation")]
    partial class AddTwoDeviceProcurementPocFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraderPro.Domain.Platform.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_device_id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_snapshot_json");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("BeforeSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_snapshot_json");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("permission_key");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("WorkspaceId", "ActorDeviceId");

                    b.HasIndex("WorkspaceId", "ActorUserId");

                    b.HasIndex("WorkspaceId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_workspace_id_occurred_at_utc");

                    b.HasIndex("WorkspaceId", "CompanyId", "BranchId");

                    b.HasIndex("WorkspaceId", "AggregateType", "AggregateId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_workspace_aggregate_history");

                    b.ToTable("audit_events", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_branch_requires_company", "branch_id IS NULL OR company_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasAlternateKey("WorkspaceId", "CompanyId", "Id")
                        .HasName("ak_branches_workspace_id_company_id_id");

                    b.HasIndex("WorkspaceId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_workspace_id_company_id_default")
                        .HasFilter("is_default");

                    b.HasIndex("WorkspaceId", "CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_workspace_id_company_id_code");

                    b.ToTable("branches", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_branches_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.CommandProbe", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Counter")
                        .HasColumnType("bigint")
                        .HasColumnName("counter");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_command_probes");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_command_probes_workspace_id_id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_command_probes_workspace_id_name");

                    b.ToTable("command_probes", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_command_probes_counter", "counter >= 0");

                            t.HasCheckConstraint("ck_command_probes_version", "version > 0");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_registration_number");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_companies_workspace_id_id");

                    b.HasIndex("WorkspaceId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_companies_workspace_id_code");

                    b.HasIndex("WorkspaceId", "TaxRegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_companies_workspace_id_tax_registration_number")
                        .HasFilter("tax_registration_number IS NOT NULL");

                    b.ToTable("companies", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_companies_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_devices_workspace_id_id");

                    b.HasIndex("WorkspaceId", "InstallationId")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_workspace_id_installation_id");

                    b.ToTable("devices", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_devices_status", "status IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("command_type");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResultPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_payload_json");

                    b.Property<int?>("ResultStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("result_status_code");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("WorkspaceId", "CommandType", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_workspace_command_key");

                    b.ToTable("idempotency_records", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_records_result_status_code", "(status = 2\n    AND result_payload_json IS NOT NULL\n    AND result_status_code BETWEEN 100 AND 599)\nOR (status <> 2 AND result_status_code IS NULL)");

                            t.HasCheckConstraint("ck_idempotency_records_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<short>("EventStream")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("event_stream");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_messages_sequence");

                    b.HasIndex("WorkspaceId", "EventStream", "Sequence")
                        .HasDatabaseName("ix_outbox_messages_workspace_id_event_stream_sequence");

                    b.HasIndex("WorkspaceId", "Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_outbox_messages_workspace_status_next_attempt");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_aggregate_version", "aggregate_version > 0");

                            t.HasCheckConstraint("ck_outbox_messages_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_messages_event_stream", "event_stream IN (1, 2)");

                            t.HasCheckConstraint("ck_outbox_messages_event_version", "event_version > 0");

                            t.HasCheckConstraint("ck_outbox_messages_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_users_workspace_id_id");

                    b.HasIndex("WorkspaceId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_workspace_id_username");

                    b.ToTable("users", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_users_status", "status IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_code");

                    b.ToTable("workspaces", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_workspaces_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Procurement.Poc.ReceivingEntryPoc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAtServerUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at_server_utc");

                    b.Property<int>("BagCount")
                        .HasColumnType("integer")
                        .HasColumnName("bag_count");

                    b.Property<string>("BagTypeReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bag_type_reference");

                    b.Property<DateTimeOffset>("CapturedAtDeviceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_device_utc");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_places");

                    b.Property<decimal>("DisplayWeightKg")
                        .HasPrecision(20, 3)
                        .HasColumnType("numeric(20,3)")
                        .HasColumnName("display_weight_kg");

                    b.Property<long>("LocalSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("local_sequence");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<decimal>("ProcessedWeightKg")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("processed_weight_kg");

                    b.Property<string>("ProcessingMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("processing_method");

                    b.Property<string>("ProductReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_reference");

                    b.Property<string>("RawWeightKg")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("raw_weight_kg");

                    b.Property<Guid>("ReceivingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiving_session_id");

                    b.Property<string>("WeightSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("weight_source");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_receiving_entry_pocs");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_receiving_entry_pocs_workspace_id_id");

                    b.HasIndex("WorkspaceId", "OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_receiving_entry_pocs_workspace_operation");

                    b.HasIndex("WorkspaceId", "ReceivingSessionId", "LocalSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_receiving_entry_pocs_workspace_session_sequence");

                    b.ToTable("receiving_entry_pocs", "procurement", t =>
                        {
                            t.HasCheckConstraint("ck_receiving_entry_pocs_bag_count", "bag_count > 0");

                            t.HasCheckConstraint("ck_receiving_entry_pocs_decimal_places", "decimal_places IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_receiving_entry_pocs_display_weight", "display_weight_kg >= 0");

                            t.HasCheckConstraint("ck_receiving_entry_pocs_local_sequence", "local_sequence > 0");

                            t.HasCheckConstraint("ck_receiving_entry_pocs_processed_weight", "processed_weight_kg >= 0");

                            t.HasCheckConstraint("ck_receiving_entry_pocs_processing_method", "processing_method IN ('Standard', 'Floor', 'Ceiling')");

                            t.HasCheckConstraint("ck_receiving_entry_pocs_weight_source", "weight_source IN ('ManualSpike', 'TestScale')");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Procurement.Poc.ReceivingFinalizationPoc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApprovedByDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_device_id");

                    b.Property<int>("FinalEntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("final_entry_count");

                    b.Property<decimal>("FinalProcessedTotalWeightKg")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("final_processed_total_weight_kg");

                    b.Property<DateTimeOffset>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at_utc");

                    b.Property<Guid>("FinalizedByDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("finalized_by_device_id");

                    b.Property<Guid>("ReceivingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiving_session_id");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_receiving_finalization_pocs");

                    b.HasIndex("WorkspaceId", "ApprovedByDeviceId");

                    b.HasIndex("WorkspaceId", "FinalizedByDeviceId");

                    b.HasIndex("WorkspaceId", "ReceivingSessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_receiving_finalization_pocs_workspace_session");

                    b.ToTable("receiving_finalization_pocs", "procurement", t =>
                        {
                            t.HasCheckConstraint("ck_receiving_finalization_pocs_entry_count", "final_entry_count > 0");

                            t.HasCheckConstraint("ck_receiving_finalization_pocs_total", "final_processed_total_weight_kg >= 0");

                            t.HasCheckConstraint("ck_receiving_finalization_pocs_version", "version > 0");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Procurement.Poc.ReceivingSessionPoc", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_device_id");

                    b.Property<long>("CloudReferenceSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cloud_reference_sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CloudReferenceSequence"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EditorDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("editor_device_id");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.Property<DateTimeOffset?>("LastLeaseHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_lease_heartbeat_at_utc");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at_utc");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<long>("NextExpectedLocalSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_expected_local_sequence");

                    b.Property<decimal>("ProcessedTotalWeightKg")
                        .HasPrecision(20, 6)
                        .HasColumnType("numeric(20,6)")
                        .HasColumnName("processed_total_weight_kg");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_receiving_session_pocs");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_receiving_session_pocs_workspace_id_id");

                    b.HasIndex("CloudReferenceSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_receiving_session_pocs_cloud_reference_sequence");

                    b.HasIndex("WorkspaceId", "ApprovedByDeviceId");

                    b.HasIndex("WorkspaceId", "EditorDeviceId");

                    b.HasIndex("WorkspaceId", "UpdatedAtUtc")
                        .HasDatabaseName("ix_receiving_session_pocs_workspace_updated_at");

                    b.HasIndex("WorkspaceId", "Status", "CloudReferenceSequence")
                        .HasDatabaseName("ix_receiving_session_pocs_workspace_status_reference");

                    b.ToTable("receiving_session_pocs", "procurement", t =>
                        {
                            t.HasCheckConstraint("ck_receiving_session_pocs_entry_count", "entry_count >= 0");

                            t.HasCheckConstraint("ck_receiving_session_pocs_lease_shape", "(status = 1\n    AND lease_id IS NOT NULL\n    AND lease_expires_at_utc IS NOT NULL\n    AND last_lease_heartbeat_at_utc IS NOT NULL)\nOR (status <> 1\n    AND lease_id IS NULL\n    AND lease_expires_at_utc IS NULL\n    AND last_lease_heartbeat_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_receiving_session_pocs_next_sequence", "next_expected_local_sequence > 0");

                            t.HasCheckConstraint("ck_receiving_session_pocs_reference_sequence", "cloud_reference_sequence > 0");

                            t.HasCheckConstraint("ck_receiving_session_pocs_status", "status IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_receiving_session_pocs_total", "processed_total_weight_kg >= 0");

                            t.HasCheckConstraint("ck_receiving_session_pocs_version", "version > 0");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.AuditEvent", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_workspaces_workspace_id");

                    b.HasOne("TraderPro.Domain.Platform.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ActorDeviceId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_devices_workspace_id_actor_device_id");

                    b.HasOne("TraderPro.Domain.Platform.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ActorUserId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_users_workspace_id_actor_user_id");

                    b.HasOne("TraderPro.Domain.Platform.Company", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CompanyId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_companies_workspace_id_company_id");

                    b.HasOne("TraderPro.Domain.Platform.Branch", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CompanyId", "BranchId")
                        .HasPrincipalKey("WorkspaceId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_branches_workspace_company_branch");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Branch", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Company", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CompanyId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_companies_workspace_id_company_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.CommandProbe", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_command_probes_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Company", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companies_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Device", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_devices_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.IdempotencyRecord", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.OutboxMessage", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_messages_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.PlatformUser", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Procurement.Poc.ReceivingEntryPoc", b =>
                {
                    b.HasOne("TraderPro.Domain.Procurement.Poc.ReceivingSessionPoc", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ReceivingSessionId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receiving_entry_pocs_sessions_workspace_session");
                });

            modelBuilder.Entity("TraderPro.Domain.Procurement.Poc.ReceivingFinalizationPoc", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ApprovedByDeviceId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receiving_finalization_pocs_devices_workspace_approver");

                    b.HasOne("TraderPro.Domain.Platform.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "FinalizedByDeviceId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receiving_finalization_pocs_devices_workspace_finalizer");

                    b.HasOne("TraderPro.Domain.Procurement.Poc.ReceivingSessionPoc", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ReceivingSessionId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receiving_finalization_pocs_sessions_workspace_session");
                });

            modelBuilder.Entity("TraderPro.Domain.Procurement.Poc.ReceivingSessionPoc", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receiving_session_pocs_workspaces_workspace_id");

                    b.HasOne("TraderPro.Domain.Platform.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ApprovedByDeviceId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_receiving_session_pocs_devices_workspace_approver");

                    b.HasOne("TraderPro.Domain.Platform.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "EditorDeviceId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receiving_session_pocs_devices_workspace_editor");
                });
#pragma warning restore 612, 618
        }
    }
}
