// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TraderPro.Infrastructure.Persistence;

#nullable disable

namespace TraderPro.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TraderProDbContext))]
    partial class TraderProDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TraderPro.Domain.Platform.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_device_id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_snapshot_json");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aggregate_type");

                    b.Property<string>("BeforeSnapshotJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_snapshot_json");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PermissionKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("permission_key");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("WorkspaceId", "ActorDeviceId");

                    b.HasIndex("WorkspaceId", "ActorUserId");

                    b.HasIndex("WorkspaceId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_workspace_id_occurred_at_utc");

                    b.HasIndex("WorkspaceId", "CompanyId", "BranchId");

                    b.HasIndex("WorkspaceId", "AggregateType", "AggregateId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_events_workspace_aggregate_history");

                    b.ToTable("audit_events", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_branch_requires_company", "branch_id IS NULL OR company_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasAlternateKey("WorkspaceId", "CompanyId", "Id")
                        .HasName("ak_branches_workspace_id_company_id_id");

                    b.HasIndex("WorkspaceId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_workspace_id_company_id_default")
                        .HasFilter("is_default");

                    b.HasIndex("WorkspaceId", "CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_workspace_id_company_id_code");

                    b.ToTable("branches", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_branches_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TaxRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tax_registration_number");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_companies_workspace_id_id");

                    b.HasIndex("WorkspaceId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_companies_workspace_id_code");

                    b.HasIndex("WorkspaceId", "TaxRegistrationNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_companies_workspace_id_tax_registration_number")
                        .HasFilter("tax_registration_number IS NOT NULL");

                    b.ToTable("companies", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_companies_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_devices_workspace_id_id");

                    b.HasIndex("WorkspaceId", "InstallationId")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_workspace_id_installation_id");

                    b.ToTable("devices", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_devices_status", "status IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("command_type");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResultPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_payload_json");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("WorkspaceId", "CommandType", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_workspace_command_key");

                    b.ToTable("idempotency_records", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_records_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aggregate_type");

                    b.Property<long>("AggregateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("aggregate_version");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer")
                        .HasColumnName("event_version");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("WorkspaceId", "Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_outbox_messages_workspace_status_next_attempt");

                    b.ToTable("outbox_messages", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_aggregate_version", "aggregate_version > 0");

                            t.HasCheckConstraint("ck_outbox_messages_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_outbox_messages_event_version", "event_version > 0");

                            t.HasCheckConstraint("ck_outbox_messages_status", "status IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("WorkspaceId", "Id")
                        .HasName("ak_users_workspace_id_id");

                    b.HasIndex("WorkspaceId", "Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_workspace_id_username");

                    b.ToTable("users", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_users_status", "status IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_workspaces_code");

                    b.ToTable("workspaces", "platform", t =>
                        {
                            t.HasCheckConstraint("ck_workspaces_status", "status IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.AuditEvent", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_events_workspaces_workspace_id");

                    b.HasOne("TraderPro.Domain.Platform.Device", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ActorDeviceId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_devices_workspace_id_actor_device_id");

                    b.HasOne("TraderPro.Domain.Platform.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ActorUserId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_users_workspace_id_actor_user_id");

                    b.HasOne("TraderPro.Domain.Platform.Company", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CompanyId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_companies_workspace_id_company_id");

                    b.HasOne("TraderPro.Domain.Platform.Branch", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CompanyId", "BranchId")
                        .HasPrincipalKey("WorkspaceId", "CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_branches_workspace_company_branch");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Branch", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Company", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "CompanyId")
                        .HasPrincipalKey("WorkspaceId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_branches_companies_workspace_id_company_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Company", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companies_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.Device", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_devices_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.IdempotencyRecord", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_records_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.OutboxMessage", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outbox_messages_workspaces_workspace_id");
                });

            modelBuilder.Entity("TraderPro.Domain.Platform.PlatformUser", b =>
                {
                    b.HasOne("TraderPro.Domain.Platform.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_workspaces_workspace_id");
                });
#pragma warning restore 612, 618
        }
    }
}
