<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TraderPro.Application\TraderPro.Application.csproj" />
    <ProjectReference Include="..\TraderPro.Domain\TraderPro.Domain.csproj" />
  </ItemGroup>
</Project>
